clockwork-dog/cogs-client-lib

package.json
src/types/CogsClientMessage.ts

This can go in first, I'll then publish a release and use that in the `cogs-client-react-lib` changes I'm making for audio, I can update the timer and hint components to use the new message types while I'm there.

Simplify subscription messages

---

src/createCogsConnnection.ts

Prevents an issue where messages sent early on can happen during the `CONNECTING` state which will throw an exception.

Check WebSocket readyState before sending messages

---

src/createCogsConnnection.ts

Handles clients with IDs such as `a/b/c`

Escape path segments in websocket URLs

---

src/CogsConnection.ts

Allows `new CogsConnection()` instead of `new CogsConnection('localhost:12095')` when developing locally. (e.g. on port 3000)

CogsConnection port defaults to 12095

---

src/CogsConnection.ts

This will allow `useIsConnected` in `cogs-client-react` to default the currect connection state to prevent a race condition between the connection and the hook being mounted.

`CogsConnection` `isConnected` getter

---

.github/workflows/npm-publish.yml
README.md

Tested locally with `act` on the `main` branch.
See https://clockwork-dog.github.io/cogs-client-lib/

Publish release docs to Github Pages

---

README.md
src/CogsConnection.ts
src/types/valueTypes.ts

Config, input port values, and output port values are saved so they can be queried later.
The new type-saftey allows you to do something like:
```ts
const connection = new CogsConnect<{
config: { foo: number },
inputPorts: { bar: 'a' | 'b' | 'c' }
}>();
const config = connection.config; //  { foo: number }
const inputPortValues = connection.inputPortValues; // { bar: 'a' | 'b' | 'c' }
```

Save config and state, `CogsConnection` type safety for events, ports, config

---

.github/workflows/npm-publish.yml
README.md
RELEASE_PROCESS.md
package.json

Tested by creating a release with a new tag `v0.17.0-rc1`.
https://www.npmjs.com/package/@clockworkdog/cogs-client/v/0.17.0-rc.1

Use version from git tag when publishing to NPM

---

src/AudioPlayer.ts
src/VideoPlayer.ts
src/types/CogsClientMessage.ts
src/types/VideoState.ts

This makes the browser download much less into memory when preloading allowing us to preload more videos.
This is important for complex project packs where we "preload" many videos, which asks the browser to download (possible all of) the video into memory.
The standard doesn't seem clear on if the entire video or just some of the video is loaded into memory.
We know from testing that `preload="metadata"` allows the video to start approximately as quickly and then streams the remaining content while playing. This uses much less RAM than `preload="auto"`.

make `preload=metadata` the default for video

---

src/VideoPlayer.ts

Playing a video and then another video when the latter's video clip player doesn't exist results in the latter not playing.

fix for playing ephemeral video when a video is already playing

---

src/helpers/urls.ts

Fixes loading files with `?` or other special URL characters in the name.

fix: URL escaping for asset files

---

tsconfig.json

While helpful when debugging, publishing source maps to NPM causes lots of warning when using `create-react-app` 5.
The options are to either:
- Publish source code along with source maps, or
- Do not ship source maps
I've opted for the latter as end users shouldn't need it. If you need source maps for some reason you can clone this repo, turn on source maps, and use `yarn link`.

do not generate source maps

---

src/CogsConnection.ts

Tested with a plugin with spaces in the folder name.

Fix double escaping in socket URLs with plugin IDs

---

src/RtspStreamer.ts

Based on our tests of playing video with a Unifi Protect camera, the video starts to lag behind over time.
Set the playback speed to 1.1 ask the browser to play slightly faster than realtime so the video is always up to date with the stream.

set RtspStreamer video playback rate to 1.1 by default

---

src/AudioPlayer.ts
src/VideoPlayer.ts

Setting the sink id is only supported on Chrome desktop so we now optionally call it to avoid crashing other browsers which don't support it. This enabled Safari web views on iOS and Chrome web views on Android to correctly play video and audio.
This does mean that it is not possible to support changing audio devices, but this is not supported on either Android or iOS anyway.

Optionally set the audio sink id when starting media playback to support non-Chrome media masters

---

src/RtspStreamer.ts
src/VideoPlayer.ts

This is required for video to autoplay on iOS.
From what I've read they should also be `muted` but we're in a webview environment we have more control over so we should be able to get this working.
I've managed to get autoplay working on iOS Safari with this change, and with the video set to `muted`, and first interacting with the page. I plan to find workarounds for the latter two issues.

add `playsinlne` for iOS

---

src/VideoPlayer.ts

Replacement for #32 
- When a video play command comes in, ensure the `video` element is created in a hidden state, and start playback
- Once playback starts, show the new video and hide the previously playing video element
- If a pause, stop, or volume change command comes in while there is a pending video, set the state to that pending video
Demo where there is a loop which switches between two videos every second
COGS behaviour:
Video running on RPi 4.6:
https://user-images.githubusercontent.com/97068/201139664-2c988274-0179-4cff-82ce-8182f86ce0f8.mp4

Allow seamless swapping between video elements when playing a video

---

src/helpers/urls.ts

using `arrayBuffer()` instead of `blob()` because the latter seems to fail on Pis in some cricumstances

fix `preloadUrl`

---

README.md

It turns out Vite isn't very happy with our library. Remove the recommendation from the README for now.

Remove Vite instructions

---

src/AudioPlayer.ts

Fixes: https://trello.com/c/rECOMM0f/2105-audio-fade-interfere-with-digital-input-trigger
Pausing clips are now handled independently in `playAudioClip`

handling pausing clip independently in playAudioClip

---

src/AudioPlayer.ts

I noticed that we default the `DEBUG` flag to true here, seems to make more sense to default to false and then this can be set to true when debugging issues.

Default to not logging debug messages in AudioPlayer

---

src/AudioPlayer.ts

Howler is stopping in progress fades when a clip is muted/unmuted (see https://github.com/goldfire/howler.js/blob/20163000723c7e1b6b226444a862b573bc1ae31d/src/howler.core.js#L1189).
This breaks when you try and fade while an existing fade is in progress, as the clip volume jumps to the end point of the existing fade.
We already guard against calling `fadeAudioPlayerVolume` based on `!IS_IOS` so the call to `mute` here was unnecessary anyway.

Remove mute from fade routine

---

package.json
src/AudioPlayer.ts
yarn.lock

Fixes #82 
- Ensure a looping clip can never restart once it is stopped
- Use forked howler.js for looping clip fix (See change here https://github.com/goldfire/howler.js/compare/v2.2.1...clockwork-dog:howler.js:fix-looping-clips?expand=1)
- Clean up some logs
Note the branch on the howler.js fork is branched off of the `v2.2.1` tag which is the version we are currently using

Fix issues that sometimes prevent looping clips from stopping properly

---

src/CogsConnection.ts
src/index.ts
src/types/CogsPluginManifestJson.ts
src/types/ManifestTypes.ts

Also renames ManifestTypes.PluginManifest to CogsPluginManifest
This makes it easier to use `CogsConnection`, e.g.
```ts
import { CogsConnection, CogsPluginManifest }  from '@clockworkdog/cogs-client';
const connection: CogsConnection<CogsPluginManifest> = ...
```
I've also renamed some types to make them more intuitive and exported some utility types.

expose CogsPluginManifest type

---

src/CogsConnection.ts

Version 2 causes an error "Attempted to assign readonly property".
I can only assume this is a relatively new feature on browsers and now the following code fails:
```ts
export class CogsConnectionOpenEvent extends Event {
public readonly type = 'open';
constructor() {
super('open');
}
}
```
which compiles to:
```js
class CogsConnectionOpenEvent extends Event {
constructor() {
super('open');
this.type = 'open';
}
}
```
Note the `this.type =` line. `Event` already has a `type` property, which is a `string` type. This was a Typescript hack to make the `type` a constant so we can do the usual Typescript discriminated union based on this `type` property. Re-defining `type` caused the error.
This change uses a new `_cogsConnectionEventType` as the discriminated key rather than `type`, which …

fix "Attempted to assign readonly property" error

---

.github/workflows/build.yml
.github/workflows/npm-publish.yml
.gitignore
package.json
yarn.lock

Replaces the `typedoc` GitHub Action and brings the build system in line with `cogs-client-react-lib`.
- build-docs script
- CI: build docs on each push
- build with Node 20

build-docs script for documentation

---

package.json
src/AudioPlayer.ts
src/CogsConnection.ts
src/VideoPlayer.ts
src/helpers/urls.ts
src/types/CogsClientMessage.ts
yarn.lock

Part of the fix for https://github.com/clockwork-dog/cogs/issues/1328
This change detects if we're in a situation where we can use a HTTP/2 server to load the assets and uses a different asset URL if we are.
On the client side this is determined by the environment we're connecting from (and the media cogs-av-box version, if applicable).
Server side is dictated by COGS sending a message to say the HTTP/2 server is supported.

Add support for loading assets through the HTTP/2 server

---

.vscode/settings.json
src/CogsConnection.ts

Required for COGS to serve optimised media based on hardware info

`assetUrl` adds query parameters with platform and screen info

---

README.md
src/CogsConnection.ts
src/DataStore.ts
src/VideoPlayer.ts
src/index.ts
src/types/CogsClientMessage.ts
src/types/CogsPluginManifest.ts

See https://github.com/clockwork-dog/cogs/issues/2466

Add `store` key/value API

---

package.json
src/CogsConnection.ts
src/helpers/urls.ts
src/types/CogsClientMessage.ts
yarn.lock

Part of https://github.com/clockwork-dog/cogs/issues/2707.
The HTTP2 asset server has been disabled for a while now and will be removed in a future COGS version. This change removes the code which would select the HTTP2 server URL and means it will always use the standard HTTP1 asset server URLs.
There is a small breaking change in this for TypeScript users as any calls to the `assetUrl` helper method with the boolean parameter will now produce a type error.

Remove the code for selecting the HTTP2 asset server
